"""removed duplicate constraint on invoice model

Revision ID: 247d6bb9aa45
Revises: 84b21e936983
Create Date: 2026-03-18 08:42:24.973761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '247d6bb9aa45'
down_revision: Union[str, Sequence[str], None] = '84b21e936983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_invoice_integration_external'), 'invoices', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_invoice_integration_external'), 'invoices', ['accounting_integration_id', 'external_invoice_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
