"""accounting integrations table

Revision ID: 2656ad70e99b
Revises: 9a068dbe6ec6
Create Date: 2026-03-01 13:31:15.085316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2656ad70e99b'
down_revision: Union[str, Sequence[str], None] = '9a068dbe6ec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'provider', name='uq_business_provider')
    )
    op.create_index(op.f('ix_accounting_integrations_business_id'), 'accounting_integrations', ['business_id'], unique=False)
    op.add_column('invoices', sa.Column('accounting_integration_id', sa.UUID(), nullable=True))
    op.add_column('invoices', sa.Column('external_invoice_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_invoices_accounting_integration_id'), 'invoices', ['accounting_integration_id'], unique=False)
    op.create_unique_constraint('uq_external_invoice_per_integration', 'invoices', ['accounting_integration_id', 'external_invoice_id'])
    op.create_foreign_key(None, 'invoices', 'accounting_integrations', ['accounting_integration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint('uq_external_invoice_per_integration', 'invoices', type_='unique')
    op.drop_index(op.f('ix_invoices_accounting_integration_id'), table_name='invoices')
    op.drop_column('invoices', 'external_invoice_id')
    op.drop_column('invoices', 'accounting_integration_id')
    op.drop_index(op.f('ix_accounting_integrations_business_id'), table_name='accounting_integrations')
    op.drop_table('accounting_integrations')
    # ### end Alembic commands ###
