"""reminder fields for invoice model

Revision ID: 3c33d4da2770
Revises: 4a89160760eb
Create Date: 2026-02-16 21:08:18.071781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c33d4da2770'
down_revision: Union[str, Sequence[str], None] = '4a89160760eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('reminder_count', sa.Integer(), nullable=False))
    op.add_column('invoices', sa.Column('last_reminder_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invoices', sa.Column('next_reminder_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invoices', sa.Column('reminders_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'reminders_enabled')
    op.drop_column('invoices', 'next_reminder_at')
    op.drop_column('invoices', 'last_reminder_at')
    op.drop_column('invoices', 'reminder_count')
    # ### end Alembic commands ###
