"""Webhook events table unique constraints

Revision ID: 4a65a063878d
Revises: 32b914bc5ee5
Create Date: 2026-03-11 13:50:42.857147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a65a063878d'
down_revision: Union[str, Sequence[str], None] = '32b914bc5ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_provider_event', 'webhook_events', ['provider', 'event_id'])
    op.drop_column('webhook_events', 'received_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_events', sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint('uq_provider_event', 'webhook_events', type_='unique')
    # ### end Alembic commands ###
