"""added balance col to  invoice model

Revision ID: 9661e44c83d1
Revises: 247d6bb9aa45
Create Date: 2026-03-30 08:44:45.606319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9661e44c83d1'
down_revision: Union[str, Sequence[str], None] = '247d6bb9aa45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'balance')
    # ### end Alembic commands ###
