"""unique constraints

Revision ID: de68c2d10fd1
Revises: 2656ad70e99b
Create Date: 2026-03-03 11:54:22.536574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de68c2d10fd1'
down_revision: Union[str, Sequence[str], None] = '2656ad70e99b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounting_integrations', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('uq_invoice_integration_external', 'invoices', ['accounting_integration_id', 'external_invoice_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_invoice_integration_external', 'invoices', type_='unique')
    op.drop_column('accounting_integrations', 'last_synced_at')
    # ### end Alembic commands ###
